# Generated by Django 4.2 on 2023-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_thumbnail_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='', verbose_name='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(null=True, unique=True, upload_to='thumbnails'),
        ),
    ]
